#ifdef MOD_ENUMS
	#define DECLARE_MOD( mod ) mod
#endif

#ifdef MOD_STRINGS
	#define DECLARE_MOD( mod ) #mod
#endif

DECLARE_MOD( MOD_UNKNOWN ),
DECLARE_MOD( MOD_SHOTGUN ),
DECLARE_MOD( MOD_GAUNTLET ),
DECLARE_MOD( MOD_MACHINEGUN ),
DECLARE_MOD( MOD_GRENADE ),
DECLARE_MOD( MOD_GRENADE_SPLASH ),
DECLARE_MOD( MOD_ROCKET ),
DECLARE_MOD( MOD_ROCKET_SPLASH ),
DECLARE_MOD( MOD_PLASMA ),
DECLARE_MOD( MOD_PLASMA_SPLASH ),
DECLARE_MOD( MOD_RAILGUN ),
DECLARE_MOD( MOD_LIGHTNING ),
DECLARE_MOD( MOD_BFG ),
DECLARE_MOD( MOD_BFG_SPLASH ),
DECLARE_MOD( MOD_WATER ),
DECLARE_MOD( MOD_SLIME ),
DECLARE_MOD( MOD_LAVA ),
DECLARE_MOD( MOD_CRUSH ),
DECLARE_MOD( MOD_TELEFRAG ),
DECLARE_MOD( MOD_FALLING ),
DECLARE_MOD( MOD_SUICIDE ),
DECLARE_MOD( MOD_TARGET_LASER ),
DECLARE_MOD( MOD_TRIGGER_HURT ),
#ifdef MISSIONPACK
DECLARE_MOD( MOD_NAIL ),
DECLARE_MOD( MOD_CHAINGUN ),
DECLARE_MOD( MOD_PROXIMITY_MINE ),
DECLARE_MOD( MOD_KAMIKAZE ),
DECLARE_MOD( MOD_JUICED ),
#endif
DECLARE_MOD( MOD_GRAPPLE )

#ifdef MOD_ENUMS
	, DECLARE_MOD( MOD_NUM_MAX )
#endif

#undef DECLARE_MOD
